# Generated by Django 4.2.7 on 2023-12-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=18)),
                ('email', models.EmailField(blank=True, max_length=50)),
            ],
        ),
    ]
